<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Shared\Gambol.Shared.fsproj" />
    <ProjectReference Include="..\..\src\Shared\dotnet\Gambol.Shared.DotNet.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Thoth.Json.Newtonsoft" Version="0.3.3" />
  </ItemGroup>
</Project>
